#!/bin/sh
alias al='code ~/.zsh_alias'
alias myzsh='code ~/.zshrc'
alias reloadzsh='source ~/.zshrc'

# git
alias git='LANG=en_US git'
alias grt='git restore'
alias grts='git restore --staged'
alias gwip='() { git commit  --no-verify -m "WIP - DO NOT PUSH: $1" }'
alias gwipa='() { git add . && gwip $1}'
alias glm="git pull origin master"
alias gbn="git symbolic-ref --short HEAD" # current branch name
alias glc="git pull origin $(gbn)"
alias gsweep="git branch --merged master | egrep -v '^\s*\*?\s*master$' | xargs git branch -d"
alias gstack='() { git reflog | grep "checkout:" | cut -d " " -f 8 | uniq | head ${1} | cat -n }'
alias ghpr="gh pr create"

# rails
alias rc='rails console'
alias rjw='rails jobs:work'
alias lt_rails="lt --port 3000 --subdomain lorenzodc1997"
alias krs="kill -9 $(lsof -wni tcp:3000 | grep ruby | awk '{print $2; exit}')"

# python
alias pm="python -m"
alias dj="python manage.py"
alias djs="python manage.py runserver"
alias djm="python manage.py migrate"

alias nginx="sudo lsof -ti:80 | sudo xargs kill -9 && sudo nginx"

# aws
alias editaws="code ~/.aws/credentials"

# misc
alias brewski="brew update && brew upgrade && brew cleanup; brew doctor"

# Amphora specific
alias hermes="cd $HOME/code/Amphora/hermes && conda activate amphora311"
alias frontend="cd $HOME/code/Amphora/frontend && conda activate base && nvm use"
